export const UI_PRESETS = {
  accentLine: 'bg-[#a2e61d]/65',
  accentLineSoft: 'bg-[#a2e61d]/60',
  accentLineStrong: 'bg-[#a2e61d]/70',
  accentLineStrongest: 'bg-[#a2e61d]/75',
  accentText: 'text-current',
  inkText: 'text-current',
  switcherBase: '!text-current',
  switcherActive: '!border-[#a2e61d]/60 !bg-[#a2e61d]/12 !text-current',
  flowDotActiveBorder: 'border-[#a2e61d]',
  flowDotActiveBg: 'bg-[#a2e61d]/70',
  accentBorder: 'border-[#a2e61d]',
  accentBorderSoft: 'border-[#a2e61d]/55',
  accentBorderLight: 'border-[#a2e61d]/40',
  accentBorderFaint: 'border-[#a2e61d]/35',
  accentBorderHover: 'hover:border-[#a2e61d]',
  accentBorderHoverSoft: 'hover:border-[#a2e61d]/70',
  accentFocusBorder: 'focus:border-[#a2e61d]',
  accentTextHover: 'hover:text-current',
  accentTextHoverBang: 'hover:!text-current',
  accentBg: 'bg-[#a2e61d]',
  accentBgSoft10: 'bg-[#a2e61d]/10',
  accentBgSoft12: 'bg-[#a2e61d]/12',
  accentBgHoverSoft12: 'hover:bg-[#a2e61d]/12',
  accentBgSoft14: 'hover:bg-[#a2e61d]/14',
  borderBase: 'border border-zinc-800',
  borderMuted: 'border border-zinc-700',
  borderTop: 'border-t border-zinc-800',
  borderBottom: 'border-b border-zinc-800',
  borderLeft: 'border-l border-zinc-800',
  borderRight: 'border-r border-zinc-800',
  borderX: 'border-x border-zinc-800',
  borderXTop: 'border-x border-t border-zinc-800',
  gridFrame: 'overflow-hidden rounded-xl border-l border-t border-zinc-800',
  gridCell: 'border-b border-r border-zinc-800',
  gridSection: 'border-x border-b border-zinc-800',
  heroSection: 'io-reveal relative overflow-hidden border-b border-zinc-800',
  flowSection: 'io-reveal section-wrap section-v-80 border-x border-b border-zinc-800',
} as const;
