export const dashboardContent = {
  header: {
    title: 'MUEL OPERATIONS CENTER',
    logout: '로그아웃',
    inviteBot: '봇 초대 링크',
  },
  realtime: {
    title: 'REALTIME BOT STATE',
    status: 'STATUS',
    online: 'ONLINE',
    offline: 'OFFLINE',
    integrityIndex: 'Integrity Index',
    connectedGuilds: 'CONNECTED GUILDS',
    trackedSources: 'TRACKED SOURCES',
  },
  tabs: {
    overview: '개요',
    sources: 'Sources',
  },
  overview: {
    radarTitle: 'Econometric Risk Radar',
    radarSubtitle: 'SYSTEMIC PROFILE',
    signalTitle: 'Live Market Signal',
    signalSubtitle: 'GLITCHED LINE TRACE',
    premiumTitle: 'Premium Insight Gate',
    premiumSubtitle: 'LOCKED PREDICTION LAYER',
    logsTitle: '실시간 로그',
    logsEmpty: '로그가 없습니다.',
    benchmarkTitle: 'UX Benchmark Summary',
    benchmarkSubtitle: 'EVENT COVERAGE',
    benchmarkTotal: 'TOTAL EVENTS',
    benchmarkUpdated: 'LAST UPDATED',
    benchmarkNoData: '아직 수집된 벤치마크 이벤트가 없습니다.',
    benchmarkTopEvents: 'TOP EVENTS',
    benchmarkTopRoutes: 'TOP ROUTES',
    quant: {
      radarMetrics: [
        { label: 'Yield Curve', value: 66 },
        { label: 'Inflation', value: 48 },
        { label: 'Demand', value: 62 },
        { label: 'Supply', value: 58 },
        { label: 'Risk Premium', value: 54 },
        { label: 'Flow', value: 69 },
      ],
      lineLabels: ['T-7', 'T-6', 'T-5', 'T-4', 'T-3', 'T-2', 'T-1', 'NOW'],
      lineValues: [58, 61, 64, 60, 66, 71, 68, 74],
      premiumRows: [
        { label: '3M Regime Forecast', value: 'Risk-On 63% / Risk-Off 37%' },
        { label: 'AI Factor Tilt', value: 'Quality + Momentum Overweight' },
        { label: 'Cross Asset Trigger', value: 'Credit Spread < 124bp' },
        { label: 'Macro Hedge Ratio', value: '0.42 Dynamic Hedge' },
      ],
    },
  },
  sourceForm: {
    title: '알림 추가',
    placeholders: {
      sourceName: '유튜브 채널 이름',
      sourceUrl: 'https://youtube.com/...',
      testUrl: '게시글 URL 입력',
    },
    selects: {
      loadingGuilds: '서버 로딩 중...',
      selectGuild: '디스코드 서버 선택',
      loadingChannels: '채널 로딩 중...',
      selectChannel: '전송 채널 선택',
      botInviteRequired: '(봇 초대 필요)',
      noCategory: '카테고리 없음',
      channelTypeForum: 'Forum',
      channelTypeNotice: 'Notice',
      channelTypeText: 'Text',
    },
    helper: {
      noBotInGuild: '선택한 서버에 봇이 없어 채널을 선택할 수 없습니다.',
      selectGuide: 'YouTube URL + 서버 + 채널을 지정하면 자동 감시가 시작됩니다.',
    },
    actions: {
      addSource: '알림 추가',
      testSend: '테스트 전송',
      delete: '삭제',
      prev: '이전',
      next: '다음',
    },
    registered: {
      title: '등록된 알림',
      totalPrefix: 'TOTAL',
      empty: '등록된 알림이 없습니다.',
      unknownInfo: '정보 없음',
      server: '서버',
      channel: '채널',
      pagePrefix: '페이지',
    },
  },
  rollingTest: {
    title: '자동 롤링 테스트',
    description: '선택한 채널로 테스트 메시지를 전송해 설정 상태를 빠르게 확인합니다.',
  },
} as const;
